In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import re
import csv
import random
import math

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn import metrics


In [2]:
filepath_train = 'train_split.csv'
df = pd.read_csv(filepath_train)
print(df.shape)
df.tail(10)

(6400, 3)


id                                               text     label
6390  6390  This movie was much better than I expected. ++...  positive
6391  6391  This is one of Joan Crawford's best Talkies. I...  positive
6392  6392  I had the privilege of seeing this film at a p...  positive
6393  6393  This almost documentary look at an enterprisin...  positive
6394  6394  So terrific, so good. I have never seen a man ...  positive
6395  6395  When the opening shot is U.S. Marines seriousl...  negative
6396  6396  This movie is not based on the bible. It compl...  negative
6397  6397  I came across this film by accident and wish I...  negative
6398  6398  80's sleazy (glam)rock is like 90's house musi...  negative
6399  6399  Over the many years, there are some films that...  positive

In [3]:
with open(filepath_train, 'r') as f:
    train_csv = f.read()

f_str = ' <br>|</br>|</ br>|<br/>|<br />|<br><br/>|<br><br />  |"\w"|;|: ' #|^([a-zA-Z]+).* |\++.*$ ^["+"]*    ,
r_str = ''
clean_csv = re.sub(f_str, r_str, train_csv)
path = './Train_clean_csv1.csv' 
with open(path, 'w') as f:
    f.write(clean_csv)

In [4]:
path_name = 'Train_clean_csv1.csv'
train_clean = pd.read_csv(path_name)
print(train_clean.shape)
train_clean.tail(10)


(6400, 3)


id                                               text     label
6390  6390  This movie was much better than I expected. ++...  positive
6391  6391  This is one of Joan Crawford's best Talkies. I...  positive
6392  6392  I had the privilege of seeing this film at a p...  positive
6393  6393  This almost documentary look at an enterprisin...  positive
6394  6394  So terrific, so good. I have never seen a man ...  positive
6395  6395  When the opening shot is U.S. Marines seriousl...  negative
6396  6396  This movie is not based on the bible. It compl...  negative
6397  6397  I came across this film by accident and wish I...  negative
6398  6398  80's sleazy (glam)rock is like 90's house musi...  negative
6399  6399  Over the many years, there are some films that...  positive

In [5]:
train_clean.label[train_clean.label == 'negative'] = 0
train_clean.label[train_clean.label == 'positive'] = 1
train_clean.head(5)

<ipython-input-5-8b76e79f4bd0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_clean.label[train_clean.label == 'negative'] = 0
<ipython-input-5-8b76e79f4bd0>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_clean.label[train_clean.label == 'positive'] = 1


id                                               text label
0   0  I have seen this movie plenty of times and I g...     1
1   1  Ho-hum. An inventor's(Horst Buchholz)deadly bi...     0
2   2  Zombie Bloodbath is a movie made by zombie fan...     1
3   3  I saw this on cable. Someone had to lose their...     0
4   4  Wow probable the worst movie i have ever seen!...     0

In [6]:
filepath_test = 'val_split.csv'
df_test = pd.read_csv(filepath_test)
print(df_test.shape)
df_test.tail(10)

(1600, 3)


id                                               text     label
1590  1590  Flashes of lightning; a sprawling cemetery; th...  positive
1591  1591  The movie is okay, it has it's moments, the mu...  positive
1592  1592  Great entertainment from start to the end. Won...  positive
1593  1593  I say "flick" because this doesn't deserve the...  negative
1594  1594  I did not like Chandni Bar from the same direc...  positive
1595  1595  Old Ed was active back in the late 1950's He w...  negative
1596  1596  Fido is a story about more well mannered zombi...  positive
1597  1597  This documentary film is based on incomplete c...  negative
1598  1598  This is a perfectly watchable adventurous movi...  positive
1599  1599  The movie has taken a little flack for playing...  positive

In [7]:
with open(filepath_test, 'r') as f:
    test_csv = f.read()

f_str = '<br>|</br>|</ br>|<br/>|<br />|<br><br/>|<br><br /> |"\w"|;|:'
r_str = ''
val_clean_csv = re.sub(f_str, r_str, test_csv)
path1 = './val_clean_csv1.csv'
with open(path1, 'w') as f:
    f.write(val_clean_csv)

In [8]:
path_name_t = 'val_clean_csv1.csv'

test_clean = pd.read_csv(path_name_t)
print(test_clean.shape)
test_clean.tail(10)


(1600, 3)


id                                               text     label
1590  1590  Flashes of lightning a sprawling cemetery the ...  positive
1591  1591  The movie is okay, it has it's moments, the mu...  positive
1592  1592  Great entertainment from start to the end. Won...  positive
1593  1593  I say "flick" because this doesn't deserve the...  negative
1594  1594  I did not like Chandni Bar from the same direc...  positive
1595  1595  Old Ed was active back in the late 1950's He w...  negative
1596  1596  Fido is a story about more well mannered zombi...  positive
1597  1597  This documentary film is based on incomplete c...  negative
1598  1598  This is a perfectly watchable adventurous movi...  positive
1599  1599  The movie has taken a little flack for playing...  positive

In [9]:
test_clean.label[test_clean.label == 'negative'] = 0
test_clean.label[test_clean.label == 'positive'] = 1
test_clean.head(5)

<ipython-input-9-1d867008acec>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_clean.label[test_clean.label == 'negative'] = 0
<ipython-input-9-1d867008acec>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_clean.label[test_clean.label == 'positive'] = 1


id                                               text label
0   0  Mighty Like A Moose is one of many short films...     1
1   1  Simply not the quality I expected from Morris ...     0
2   2  Just saw the World Preem of Fido at the Toront...     1
3   3  ...this is a classic with so many great dialog...     1
4   4  It's hard to believe that in 1997 David Duchov...     0

In [10]:
print(train_clean)
print(test_clean)

        id                                               text label
0        0  I have seen this movie plenty of times and I g...     1
1        1  Ho-hum. An inventor's(Horst Buchholz)deadly bi...     0
2        2  Zombie Bloodbath is a movie made by zombie fan...     1
3        3  I saw this on cable. Someone had to lose their...     0
4        4  Wow probable the worst movie i have ever seen!...     0
...    ...                                                ...   ...
6395  6395  When the opening shot is U.S. Marines seriousl...     0
6396  6396  This movie is not based on the bible. It compl...     0
6397  6397  I came across this film by accident and wish I...     0
6398  6398  80's sleazy (glam)rock is like 90's house musi...     0
6399  6399  Over the many years, there are some films that...     1

[6400 rows x 3 columns]
        id                                               text label
0        0  Mighty Like A Moose is one of many short films...     1
1        1  Simply not 

In [11]:
#PART 2

In [12]:


#Frequency Count
#Train_CSV

train_vectorizer = CountVectorizer()
train_vectorizer.fit(train_clean.text)
#print(train_vectorizer.vocabulary_)
train_vector = train_vectorizer.transform(train_clean.text)
print(train_vector.shape)
print(type(train_vector))

print(train_vector.toarray())



(6400, 45622)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
test_vector = train_vectorizer.transform(test_clean.text)
print(test_vector.shape)
print(type(test_vector))
print(test_vector.toarray())


(1600, 45622)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 4 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
# TFIDF Count
#Train_CSV



from sklearn.feature_extraction.text import TfidfVectorizer

train_vectorizer_tfidf = TfidfVectorizer(use_idf=True)
fitted_vectorizer=train_vectorizer_tfidf.fit(train_clean.text)

train_vector_tfidf=fitted_vectorizer.transform(train_clean.text)
print(train_vector_tfidf.shape)
print(train_vector_tfidf.toarray())

(6400, 45622)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [15]:
# TFIDF Count
#Test_CSV


test_vector_tfidf=fitted_vectorizer.transform(test_clean.text)
print(test_vector_tfidf.shape)
print(test_vector_tfidf.toarray())



(1600, 45622)
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.19310835 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


'test_vectorizer_tfidf = TfidfVectorizer()\n\ntest_vectorizer_tfidf.fit(test_clean.review)\n\n#print(test_vectorizer_tfidf.vocabulary_)\nprint(test_vectorizer_tfidf.idf_)\ntest_vector_tfidf = test_vectorizer_tfidf.transform([test_clean.review[0]])\nprint(test_vector_tfidf.shape)\nprint(test_vector_tfidf.toarray())'

In [16]:
#Binary Occurance
#Train_CSV


train_vectorizer_b = HashingVectorizer(binary = True)

train_vector_b = train_vectorizer_b.transform(train_clean.text)

print(train_vector_b.shape)
print(train_vector_b.toarray())

(6400, 1048576)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
#Binary Occurance
#Test_CSV

test_vector_b = train_vectorizer_b.transform(test_clean.text)
print(test_vector_b.shape)
print(test_vector_b.toarray())


(1600, 1048576)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


'\ntest_vectorizer_b = HashingVectorizer(binary = True)\n\ntest_vector_b = test_vectorizer_b.transform(test_clean.review)\n\nprint(test_vector_b.shape)\nprint(test_vector_b.toarray())'

In [18]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix


In [19]:
#Frequency Vector

y_train = train_clean.label
X_train = train_vector

y_test = test_clean.label
X_test = test_vector


#X_train = X_train.todense()
X_train = X_train.toarray()
y_train=y_train.astype('int')


#X_test = X_test.todense()
X_test = X_test.toarray()
y_test=y_test.astype('int')


print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)



(6400, 45622)
(6400,)
(1600, 45622)
(1600,)


In [41]:
""" Frequency Multinomial NB"""

f_mnb = MultinomialNB()

f_mnb.fit(X_train, y_train)
y_pred = f_mnb.predict(X_test)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_pred)
accuracy = metrics.accuracy_score(y_test, y_pred)
print ("\n Accuracy = ")
print(accuracy)

[1 1 1 ... 0 1 1]

 Accuracy = 
0.829375


In [42]:
""" Frequency Multinomial NB"""

print("Macro Precision_score:", precision_score(y_test, y_pred, average='macro'))
print("Macro Recall_score:", recall_score(y_test, y_pred, average='macro'))
print("Macro F1_score:", f1_score(y_test, y_pred, average='macro'))

Macro Precision_score: 0.8300066533599468
Macro Recall_score: 0.829375
Macro F1_score: 0.8292933141835449


In [43]:
""" Frequency Gaussian NB"""

f_gnb = GaussianNB()

f_gnb.fit(X_train, y_train)
y_pred = f_gnb.predict(X_test)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_pred)
accuracy = metrics.accuracy_score(y_test, y_pred)
print ("\n Accuracy = ")
print(accuracy)

[1 0 1 ... 0 0 1]

 Accuracy = 
0.630625


In [44]:
""" Frequency Gaussian NB"""

print("Macro Precision_score:", precision_score(y_test, y_pred, average='macro'))
print("Macro Recall_score:", recall_score(y_test, y_pred, average='macro'))
print("Macro F1_score:", f1_score(y_test, y_pred, average='macro'))


""" Frequency Gaussian NB"""

Macro Precision_score: 0.6326565100864965
Macro Recall_score: 0.630625
Macro F1_score: 0.6292054071074453


' Frequency Gaussian NB'

In [24]:
#TFIDF Vector

y_train_tf = train_clean.label
X_train_tf = train_vector_tfidf

y_test_tf = test_clean.label
X_test_tf = test_vector_tfidf


#X_train = X_train.todense()
X_train_tf = X_train_tf.toarray()
y_train_tf=y_train_tf.astype('int')


#X_test = X_test.todense()
X_test_tf = X_test_tf.toarray()
y_test_tf=y_test_tf.astype('int')


print(X_train_tf.shape)
print(y_train_tf.shape)
print(X_test_tf.shape)
print(y_test_tf.shape)



(6400, 45622)
(6400,)
(1600, 45622)
(1600,)


In [45]:
""" TFIDF Multinomial NB"""

tf_Mnb = MultinomialNB()

tf_Mnb.fit(X_train_tf, y_train_tf)
y_pred_tf = tf_Mnb.predict(X_test_tf)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_pred_tf)
accuracy_tf = metrics.accuracy_score(y_test_tf, y_pred_tf)
print ("\n Accuracy = ")
print(accuracy_tf)

[1 1 1 ... 0 1 1]

 Accuracy = 
0.84375


In [46]:
""" TFIDF Multinomial NB"""

print("Macro Precision_score:", precision_score(y_test_tf, y_pred_tf, average='macro'))
print("Macro Recall_score:", recall_score(y_test_tf, y_pred_tf, average='macro'))
print("Macro F1_score:", f1_score(y_test_tf, y_pred_tf, average='macro'))

Macro Precision_score: 0.8473998698829579
Macro Recall_score: 0.84375
Macro F1_score: 0.8433385188283602


In [47]:
""" TFIDF Gaussian NB"""

tf_gnb = GaussianNB()

tf_gnb.fit(X_train_tf, y_train_tf)
y_pred_tf = tf_gnb.predict(X_test_tf)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_pred_tf)
accuracy_tf = metrics.accuracy_score(y_test_tf, y_pred_tf)
print ("\n Accuracy = ")
print(accuracy_tf)

[1 0 1 ... 0 0 1]

 Accuracy = 
0.621875


In [48]:
""" TFIDF Gaussian NB"""

print("Macro Precision_score:", precision_score(y_test_tf, y_pred_tf, average='macro'))
print("Macro Recall_score:", recall_score(y_test_tf, y_pred_tf, average='macro'))
print("Macro F1_score:", f1_score(y_test_tf, y_pred_tf, average='macro'))

""" TFIDF Gaussian NB"""

Macro Precision_score: 0.6219178617482708
Macro Recall_score: 0.621875
Macro F1_score: 0.6218417634362394


' TFIDF Gaussian NB'

In [31]:


filepath_pred = 'test_split.csv'
df_pred = pd.read_csv(filepath_pred)
print(df_pred.shape)
df_pred.tail(10)

(2000, 2)


id                                               text
1990  1990  The antiwar musical "Hair" is my number one cu...
1991  1991  Just lovely. It is long. No climax. Don't wait...
1992  1992  I'm impressed that 'Hail the Woman' was made a...
1993  1993  Although the video box for many copies of this...
1994  1994  This is the most depressing film I have ever s...
1995  1995  I really like Traci Lords. She may not be the ...
1996  1996  I saw this movie because every review I read o...
1997  1997  After a long run in the West End this charming...
1998  1998  I guess if a film has magic, I don't need it t...
1999  1999  As a camera operator, I couldn't help but admi...

In [32]:
with open(filepath_pred, 'r') as f:
    pred_csv = f.read()

f_str = ' <br>|</br>|</ br>|<br/>|<br />|<br><br/>|<br><br />  |"\w"|;|: ' #|^([a-zA-Z]+).* |\++.*$ ^["+"]*    ,
r_str = ''
pred_clean_csv = re.sub(f_str, r_str, pred_csv)
path = './pred_clean_csv.csv' 
with open(path, 'w') as f:
    f.write(pred_clean_csv)

In [34]:
pred_path_name = 'pred_clean_csv.csv'
pred_clean = pd.read_csv(pred_path_name)
print(pred_clean.shape)
pred_clean.tail(10)

(2000, 2)


id                                               text
1990  1990  The antiwar musical "Hair" is my number one cu...
1991  1991  Just lovely. It is long. No climax. Don't wait...
1992  1992  I'm impressed that 'Hail the Woman' was made a...
1993  1993  Although the video box for many copies of this...
1994  1994  This is the most depressing film I have ever s...
1995  1995  I really like Traci Lords. She may not be the ...
1996  1996  I saw this movie because every review I read o...
1997  1997  After a long run in the West End this charming...
1998  1998  I guess if a film has magic, I don't need it t...
1999  1999  As a camera operator, I couldn't help but admi...

In [38]:


#frequency Pred
pred_vector = train_vectorizer.transform(pred_clean.text)
print(pred_vector.shape)
print(type(pred_vector))
print(pred_vector.toarray())

X_pred_freq = pred_vector



(2000, 45622)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
# TFIDF Count
#Pred_CSV


pred_vector_tfidf=fitted_vectorizer.transform(pred_clean.text)
print(pred_vector_tfidf.shape)
print(pred_vector_tfidf.toarray())


X_pred_tfidf = pred_vector_tfidf

(2000, 45622)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [50]:
""" Frequency Multinomial NB"""

y_final_pred_f_Multi = f_mnb.predict(X_pred_freq)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_final_pred_f_Multi)
print(y_final_pred_f_Multi.shape)


[1 0 0 ... 1 1 1]
(2000,)


In [56]:
y_final_pred_f_Multi = pd.DataFrame(y_final_pred_f_Multi, columns=['label']).to_csv('Freq_Multinomial.csv')

In [52]:
""" Frequency GAUSSIAN NB """

X_pred_freq = X_pred_freq.toarray()

y_final_pred_f_gau = f_gnb.predict(X_pred_freq)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_final_pred_f_gau)


[1 0 0 ... 1 1 0]


In [57]:
y_final_pred_f_gau = pd.DataFrame(y_final_pred_f_gau, columns=['label']).to_csv('Freq_Gau.csv')

In [53]:
""" TFIDF Multinomial NB"""

y_final_pred_tfidf_mul = tf_Mnb.predict(X_pred_tfidf)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_final_pred_tfidf_mul)


[1 0 0 ... 1 1 1]


In [58]:
y_final_pred_tfidf_mul = pd.DataFrame(y_final_pred_tfidf_mul, columns=['label']).to_csv('TFIDF_Multi.csv')

In [55]:
""" TFIDF Gaussian NB"""

X_pred_tfidf = X_pred_tfidf.toarray()

y_final_pred_tfidf_gau = tf_gnb.predict(X_pred_tfidf)
#y_pred = pd.DataFrame(y_pred, columns=['close_label_day_5']).to_csv('y_pred.csv') RUN ON SHELL
print(y_final_pred_tfidf_gau)


[1 0 0 ... 1 1 0]
